---
## CNPRC Admins update with Critical and Security patches only.
## Visit https://docs.ansible.com/ansible/latest/win_updates_module.html
## for a full list of options.

- hosts: all

  tasks:
  # Check if there are missing updates
  - block:
    - name: Check for missing updates.
      win_updates:
        state: searched
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
      register: update_count
      ignore_errors: yes

  # Inistall missing updates
  - block:
    - name: Install missing updates.
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
      register: update_result

    - name: Reboot
      win_reboot:
        reboot_timeout: 300

