---
- hosts: all
  become: true
  gather_facts: False
  vars:
    ## 
    ##Enter in the file name as it appears on the LabKey update page
    ##
    lbky_cnprc_file: LabKey18.2-SNAPSHOT-58506.512-cnprc-bin.tar.gz
    ##
    ##
    lbky_download_dir: /opt/lbky
    lbky_aws_url: http://labkey.s3.amazonaws.com/downloads/cnprc/d/trunk
    lbky_extract: "{{ lbky_cnprc_file | regex_replace('.tar.gz') }}"
    lbky_home: /usr/local/labkey

  handlers:
    - name: Wait for system.
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=30 timeout=60
      become: False

  tasks:
    - name: Create LabKey home directory
      file:
        path: "{{ lbky_home }}"
        state: directory
        mode: 0755

    - name: Create download directory for LabKey pull
      file:
        path: "{{ lbky_download_dir }}"
        state: directory
        mode: 0755

#    - name: Download and Unarchive LabKey
#      unarchive:
#        src: "{{ lbky_aws_url }}/{{ lbky_cnprc_file }}"
#        dest: "{{ lbky_download_dir }}"
#        remote_src: yes

    - name: Copy LabKey JAR files to tomcat-home/lib folder
      copy:
        src: "{{ lbky_download_dir }}/{{ lbky_extract }}/tomcat-lib/{{ item }}"
        dest: /opt/tomcat/lib/
        owner: tomcat
        group: tomcat
        remote_src: yes
      with_items:
        - jtds.jar
        - mail.jar
        - mysql.jar
        - postgresql.jar
        - labkeyBootstrap.jar

    - name: Copy LabKey directories to Labkey home
#      copy:
      synchronize:
        src: "{{ lbky_download_dir }}/{{ lbky_extract }}/{{ item }}"
        dest: "{{ lbky_home }}"
#        remote_src: yes
      with_items:
        - labkeywebapp
        - modules
        - pipeline-lib
      delegate_to: "{{ inventory_hostname }}"

    - name: Reboot the server
      shell: sleep 2 && /sbin/shutdown -r now "Tomcat installed"
      async: 1
      poll: 0
      ignore_errors: true
      notify:
        - Wait for system.
      when: file.stat.exists == true
