---
- hosts: all
  become: true
  gather_facts: False
  vars:
    ## 
    ##Enter in the file name as it appears on the LabKey update page
    ##
    lbky_cnprc_file: LabKey18.2-SNAPSHOT-58506.512-cnprc-bin.tar.gz
    ##
    ##
    lbky_download_dir: /opt/lbky
    lbky_aws_url: http://labkey.s3.amazonaws.com/downloads/cnprc/d/trunk
    lbky_extract: "{{ '{{ lbky_cnprc_file }}' | regex_replace('.tar.gz') }}"

  handlers:
    - name: Wait for system.
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=30 timeout=60
      become: False

  tasks:
    - name: Create download directory for LabKey pull
      file:
        path: "{{ lbky_download_dir }}"
        state: directory
        mode: 0755

    - name: Download and Unarchive LabKey
      unarchive:
        src: "{{ lbky_aws_url }}/{{ lbky_cnprc_file }}"
        dest: "{{ lbky_download_dir }}"
        remote_src: yes
        register: lbky_archive
        debug:
          msg: "{{ lbky_archive.stdout }}"

#    - name: Move LabKey JAR files to tomcat-home/lib folder
#      command: mv /opt/apache-tomcat-8.5.9 /opt/tomcat

    - name: Reboot the server
      shell: sleep 2 && /sbin/shutdown -r now "Tomcat installed"
      async: 1
      poll: 0
      ignore_errors: true
      notify:
        - Wait for system.
      when: file.stat.exists == true
