---
- hosts: all
  become: true
  gather_facts: False

  tasks:
   - name: Rebooting the Kiosk
     shell: sleep 2 && shutdown -r now
     async: 1
     poll: 0
     ignore_errors: true

   - name: Wait for reboot
     local_action: wait_for host={{ ansible_ssh_host  }} state=started port=22 delay=30
     become: false
