--- 
- hosts: all
  serial: 1
  gather_facts: False
  vars:
    timestamp: "{{lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
  connection: local
  
  tasks:
    - name: Take Snapshot of Guest VM
      vmware_guest_snapshot:
        validate_certs: false
        username: "{{ ansible_env.VMWARE_USER }}"
        password: "{{ ansible_env.VMWARE_PASSWORD }}"
        hostname: "{{ ansible_env.VMWARE_HOST }}"
        datacenter: CNPRC
        
## For each Host in the Inventory, retrieves Name and UUID from the Hosts Variables.
        uuid: "{{ config.uuid }}"
        state: present
        snapshot_name: 'Snapshot_{{ timestamp }}'
        description: Automated PM snapshot from Ansible.
      delegate_to: localhost
