--- 
- hosts: all
  serial: 1
  gather_facts: False
  vars_prompt:
    - name: "vcenter_password"
      prompt: "vCenter Password"
  connection: local
  
  tasks:
  #Get date
  - set_fact:  timestamp="{{lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
  
  # Take snapshot
  - name: Take Snapshot of Guest VM
    vmware_guest_snapshot:
      validate_certs: false
      hostname: "169.237.80.110"
      username: "administrator@vsphere.local"
      password: "{{ vcenter_password }}"
      datacenter: CNPRC
        
## For each Host in the Inventory, retrieves Name and UUID from the Hosts Variables.
      uuid: "{{ config.uuid }}"
      state: present
      snapshot_name: 'Snapshot_{{ timestamp }}'
      description: Automated PM snapshot from Ansible.
    delegate_to: localhost
