---    
    - name: Wait for connection
      wait_for_connection:
        delay: 30
        timeout: 300
      
  # Install MSSQL packag
    - name: Import MS GPG Key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Register MSSQL Repo
      get_url:
        url: "{{ ubuntu_server_repo_url }}"
        dest: /etc/apt/sources.list.d/mssql-server.list

    - name: Refresh apt-get cache for MSSQL Server repo
      apt:
        update_cache: yes

    - name: Install MSSQL
      package:
        name: mssql-server
      state: latest
    
    - name: MSSQL Server setup
      mssql_conf:
       setup_sa_password: "{{ sa_password }}"
       setup_pid: "{{ pid }}"
       login_name: 'sa'
       login_password: "{{ sa_password }}"
       
# TSQL endpoint

    - name: set TSQL endpoint port
      mssql_conf:
        name: network.tcpport
        value: "{{ tsql_endpoint_port }}"
        login_name: 'sa'
        login_password: "{{ sa_password }}"

    - name: open TSQL endpoint in firewall (Ubuntu)
      ufw:
        port: "{{ tsql_endpoint_port }}"
        proto: tcp
        rule: allow

# mssql-tools package

    - name: Install MSSQL tool repo
      get_url:
        url: "{{ ubuntu_tools_repo_url }}"
        dest: /etc/apt/sources.list.d/mssql-tools.list

    - name: Refresh apt-get cache for MSSQL tools repo
      apt:
        update_cache: yes

    - name: Install MSSQL tools package
      apt:
        name: mssql-tools
        state: latest
      environment:
        ACCEPT_EULA: 'y'

    - name: Install UNIXODBC package
      apt:
        name: unixodbc-dev
        state: latest

# Start MSSQL service

    - name: Start MSSQL
      service:
        name: mssql-server
        state: started

    - name: Check if a reboot is required
      register: file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the server
      shell: sleep 2 && /sbin/shutdown -r now "Tomcat installed"
      async: 1
      poll: 0
      ignore_errors: true
      notify:
        - Wait for system.
      when: file.stat.exists == true
